### ISSUE TITLE
Issue executing ssm-diff init

### ISSUE THREAD

**Issue by applike-ss** [runtheops/ssm-diff#8]
Expected Output:
* Something like 'ssm repo initialized'

Actual Output:
* 'int' object has no attribute 'splitlines'

Python Version: Python 2.7.15rc1
OS: Ubuntu Linux 18.04 upgraded from 16.04

If you need any further information, please let me know.
I'm not into python development, so i don't know what and how to provide.

**Comment by applike-ss** [comment]
Using a virtual env with python 3.6 works, so feel free to either close it or to add a mentioning in the readme for others that might accidentally try to use it the same way i did.

**Comment by runtheops** [comment]
Hi @applike-ss,

Thanks for the feedback, and sorry for not stating out explicitly that Python 3 is required.
Will update readme accordingly

**Comment by applike-ss** [comment]
thanks! maybe even some more insight what requirements have to be met are useful as well. I changed the interpreter manually by changing the symlink of /usr/bin/python to the 3 version but that didn't help.
Would you add a suggestion to use a venv for other users to the readme? maybe that will help other people as well. (Or they know that this is in general a good idea to separate your working envs)
Nice tool!
